### ISSUE TITLE
Issue with Read function due to incorrect mail numbering

### ISSUE THREAD

**Issue by Chamo1** [jacksonbenete/email_terminal#45]
Noticed that with the latest sync that numbering of emails will display in chronological order (e.g., _0,1,2, etc_.) over the actual index number appropriate for the email on a user's Mail list. Previously if a user was assigned emails 1 and 3 on mailserver.json, then when they checked their mail list it would display _[1] Email1_ and _[3] Email3_. However, now it displays _[0] Email1_ and _[1] Email3_. Due to the displayed numbers not matching with the actual mail's index, the user will now just get a Invalid Message Key Error unless they guess what the right index number for the relevant email is.

Included screenshot example of the issue:
![image](https://github.com/jacksonbenete/email_terminal/assets/13954636/ed5a442e-64ee-47de-af93-f9c3d2bd01f2)
![image](https://github.com/jacksonbenete/email_terminal/assets/13954636/c188733c-d9d1-4674-89b1-8a73fff6788c)

For the above, user should see _[2] Contrato n22_ as that is number necessary to be input when using the Read function to actually see that mail item.

**Comment by Chamo1** [comment]
Saw [BadDevilGrind](https://github.com/BadDevilGrind)'s Issue and his included fix resolved the problem.

**Comment by Lucas-C** [comment]
Thank you for the report @Chamo1!

I missed @BadDevilGrind report in issue https://github.com/jacksonbenete/email_terminal/issues/44 and I will check this right now.
